Repository hannemariavister/terraform-nomad-nifi, pull requests merged in 2021-01, with the labels that each got.

#31 Health check for nifi-registry in nifi
  CHANGELOG.md
  conf/nomad/nifi.hcl
Labels: enhancement

#33 update vagrant box
  CHANGELOG.md
  Vagrantfile.default
Labels: enhancement

#37 Release 0.1.1
  CHANGELOG.md
Labels: patch

#41 Created a new example `standalone_git` with NiFi Registry integrated with GIT.
  .gitignore
  CHANGELOG.md
  LICENSE
  Makefile
  README.md
  Vagrantfile
  Vagrantfile.default
  dev/ansible/01_run_terraform.yml
  dev/ansible/02_run_terraform.yml
  example/README.md
  example/resources/images/nifi_and_nifiregistry_git.png
  example/standalone_git/README.md
  example/standalone_git/main.tf
  example/standalone_git/providers.tf
  example/standalone_git/variables.tf
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  example/vagrant_box_example/nomad_acl.tf
  getting_started_modules.md
  getting_started_vagrantbox.md
  main.tf
  nomad/README.md
  nomad/nifi.hcl
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/00_create_intention.yml
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/03_healthcheck_test.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/bootstrap/README.md
  template_example/dev/vagrant/bootstrap/consul/post/510-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/post/520-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/510-prestart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/520-prestart-example.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/standalone/main.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
Labels: enhancement

#44 Refactor example standalone
  CHANGELOG.md
  example/standalone/README.md
  example/standalone/main.tf
  example/standalone_git/main.tf
  main.tf
  variables.tf
Labels: documentation
