Repository hannemariavister/terraform-nomad-nifi, pull requests merged in 2021-02, with the labels that each got.

#54 Secrets managed by vault and consul-template (support Git integration for Nifi registry)
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
  README.md
  dev/ansible/01_put_secrets_vault.yml
  dev/ansible/02_put_variables_consul.yml
  dev/ansible/03_run_terraform.yml
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  example/standalone/main.tf
  example/standalone_git/README.md
  example/standalone_git/main.tf
  main.tf
  variables.tf
Labels: enhancement

#56 Ny release
  CHANGELOG.md
Labels: minor

#58 Fixed bug in CI/CD test (GitHub actions)
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  nomad/nifi.hcl
Labels: bug, priority/high

#60 Deleted unused variables in vault secret
  CHANGELOG.md
  README.md
  example/standalone_git/main.tf
  main.tf
  variables.tf
Labels: patch

#63 Release 0.5.0
  CHANGELOG.md
Labels: minor
